name: Docker CI/CD

# on:
#   push:
#     branches: [master]
on: []

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudiot-node:latest

  deploy-to-ec2:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop cloudiot-container || true
            docker rm cloudiot-container || true

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cloudiot-node:latest

            docker run -d --name cloudiot-container -p 8080:8080 \
              -p 1883:1883 \
              -e NODE_ENV=production \
              -e PORT=8080 \
              -e PORT=1883 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e FITBIT_CLIENT_ID=${{ secrets.FITBIT_CLIENT_ID }} \
              -e FITBIT_CLIENT_SECRET=${{ secrets.FITBIT_CLIENT_SECRET }} \
              -e FITBIT_REDIRECT_URI=${{ secrets.FITBIT_REDIRECT_URI }} \
              -e FITBIT_SCOPE="${{ secrets.FITBIT_SCOPE }}" \
              ${{ secrets.DOCKERHUB_USERNAME }}/cloudiot-node:latest
